/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Configurações do Supabase via variáveis de ambiente
export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "vwiumednzppcianfuynd"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3aXVtZWRuenBwY2lhbmZ1eW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1Njk3MDksImV4cCI6MjA3NDE0NTcwOX0.woBGeN2KxU0BRJJCDIEoVjA7XkMdY9L_MvagPKkhnyI"
export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "https://vwiumednzppcianfuynd.supabase.co"